import { absoluteSiteUrl, sitePath } from "../../lib/site";

export const metadata = { title: "Privacy in FlashLock", description: "A plain-language guide to FlashLock’s local study data, Android permissions and optional usage sharing.", alternates: { canonical: absoluteSiteUrl("/privacy/") }, openGraph: { title: "Privacy in FlashLock", description: "A plain-language guide to FlashLock’s local study data, Android permissions and optional usage sharing.", type: "website", url: absoluteSiteUrl("/privacy/") } };
export default function Privacy(){return <main className="policyPage">
<a className="brand" href={sitePath("/")}><img src={sitePath("/app/flashlock-icon.svg")} width="36" height="36" alt=""/>FlashLock</a>
<p className="eyebrow">YOUR LEARNING IS PERSONAL</p><h1>Privacy in FlashLock</h1><p>Updated 30 September 2026 · Android beta 1.0.84</p>
<p className="policyNote">Your decks and study progress are stored on your device. Sharing app-usage analytics is optional and off until you turn it on.</p>
<h2>Your cards and progress</h2><p>FlashLock stores imported and created cards, deck names, review history, card colours, settings, and your chosen apps and websites locally. The website’s interactive card demo does not save study progress.</p>
<h2>Android permissions</h2><p>Accessibility and Usage Access help FlashLock recognise when a selected app or website is in use and show a study break. The app uses this information for the blocking rules you choose. Card text, deck names and browsing history are not included in FlashLock’s usage-analytics events. You can disable these permissions in Android Settings.</p><p>The floating countdown uses Android’s display-over-other-apps permission. Notifications and background-access settings help keep its status visible and its service running.</p>
<h2>Optional app-usage sharing</h2><p>If you choose “Share app usage” in the tutorial or under Settings → About, FlashLock uses Google Analytics for Firebase to receive usage and performance events. Examples include review counts, import success or failure, and speech-start timing. The service can also process technical information such as app version, device information and an app-instance identifier.</p><p>This is separate from your personal Progress tab, which works without sharing. You can turn sharing off in Settings. Turning it off stops future collection through this feature; it does not automatically delete data already received by Google. Advertising-ID collection and ad-personalisation consent are disabled in the app configuration.</p><p>More about the provider: <a href="https://firebase.google.com/support/privacy">Firebase privacy and security</a>.</p>
<h2>Speech, language detection and AI tools</h2><p>Read-aloud uses your phone’s text-to-speech provider. Depending on the voice and provider, speech and voice downloads may use the internet and are subject to that provider’s settings. Language identification uses Google ML Kit; its SDK is also subject to Google’s service and privacy terms.</p><p>The AI workflow helps you copy a prompt into an AI tool of your choice and paste the result back. Information you choose to send to that tool is handled under its own policies. FlashLock does not send your deck to an AI service in the background.</p>
<h2>Deleting and sharing local data</h2><p>You can remove cards and decks inside FlashLock. Clearing the app’s storage or uninstalling removes its local data; Android device backup and restore behaviour is controlled separately by your device settings. Files you import from or share with other apps remain subject to those apps’ storage and sharing settings.</p>
<h2>This website</h2><p>This homepage does not add advertising or analytics scripts, newsletter tracking or a signup database. The site is publicly hosted on GitHub Pages. GitHub processes the technical requests needed to serve its pages and files.</p>
<p><a href={sitePath("/")}>← Back to FlashLock</a></p>
</main>}
